package com.gentics.dependency.reporting.composer.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * POJO of a dependencies report generated by <code>composer</code>.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class DependencyReport {
	/**
	 * List of locked dependencies
	 */
	private List<Dependency> locked;

	/**
	 * Get the dependencies
	 * @return list of dependencies
	 */
	public List<Dependency> getLocked() {
		return locked;
	}

	/**
	 * Set the dependencies
	 * @param locked list of dependencies
	 * @return fluent API
	 */
	public DependencyReport setLocked(List<Dependency> locked) {
		this.locked = locked;
		return this;
	}
}
